FROM node:18

# Establecer directorio de trabajo
WORKDIR /srv/app

# Instalar dependencias de Strapi y MySQL2
RUN npm install mysql2

# Exponer el puerto de Strapi
EXPOSE 1337

# Comando por defecto para iniciar Strapi
CMD ["strapi", "start"]
